# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_A_B.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chart(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.pushButton_A = QtWidgets.QPushButton(Form)
        self.pushButton_A.setGeometry(QtCore.QRect(240, 40, 75, 23))
        self.pushButton_A.setObjectName("pushButton_A")
        self.pushButton_B = QtWidgets.QPushButton(Form)
        self.pushButton_B.setGeometry(QtCore.QRect(490, 40, 75, 23))
        self.pushButton_B.setObjectName("pushButton_B")
        self.widget_chart = QtWidgets.QWidget(Form)
        self.widget_chart.setGeometry(QtCore.QRect(70, 150, 491, 271))
        self.widget_chart.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.widget_chart.setObjectName("widget_chart")
        self.pushButton_Done = QtWidgets.QPushButton(Form)
        self.pushButton_Done.setGeometry(QtCore.QRect(480, 90, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Done.setFont(font)
        self.pushButton_Done.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.pushButton_Done.setObjectName("pushButton_Done")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(70, 60, 491, 22))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_A = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_A.setObjectName("lineEdit_A")
        self.gridLayout.addWidget(self.lineEdit_A, 0, 0, 1, 1)
        self.lineEdit_B = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_B.setObjectName("lineEdit_B")
        self.gridLayout.addWidget(self.lineEdit_B, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_A.setText(_translate("Form", "Browse.."))
        self.pushButton_B.setText(_translate("Form", "Browse.."))
        self.pushButton_Done.setText(_translate("Form", "Done!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
