# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage

import cv2
import imutils
import time

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from ui import activeSupwin as avsw
from processImg import camProcess

class Ui_MainWindow(object):

        def __init__(self) -> None:
                self.process_l = []
                self.process_r = []
                self.Procam = camProcess.ProcessCam()
                self.activeSud = avsw.active_sub_win()
                self.timeM = QtCore.QTimer()
                self.video0 = None
                self.video1 = None

                self.is_run = False

                self.i = 0

                self.timer_fine = QtCore.QTimer()
                self.timer_fine.setInterval(5000)
                self.timer_fine.setSingleShot(True)

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.setWindowModality(QtCore.Qt.WindowModal)
                MainWindow.resize(1200, 709)
                MainWindow.setStyleSheet("background-color: rgb(184, 184, 184);")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.test = QtWidgets.QPushButton(self.centralwidget)
                self.test.setGeometry(QtCore.QRect(930, 80, 100, 71))
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.test.setFont(font)
                self.test.setStyleSheet("background-color: rgb(255, 170, 0);")
                self.test.setObjectName("test")
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.setGeometry(QtCore.QRect(930, 460, 111, 61))
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(18)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_2.setFont(font)
                self.pushButton_2.setStyleSheet("background-color: rgb(85, 170, 0);\n"
                                                "")
                self.pushButton_2.setObjectName("pushButton_2")
                self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_3.setGeometry(QtCore.QRect(1060, 460, 111, 61))
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(18)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_3.setFont(font)
                self.pushButton_3.setStyleSheet("background-color: rgb(170, 0, 0);")
                self.pushButton_3.setObjectName("pushButton_3")
                self.setting_process = QtWidgets.QToolButton(self.centralwidget)
                self.setting_process.setGeometry(QtCore.QRect(1130, 390, 61, 51))
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(18)
                self.setting_process.setFont(font)
                self.setting_process.setStyleSheet("border-color: rgb(0, 0, 0);\n"
                                                "background-color: rgb(240, 240, 240);")
                self.setting_process.setObjectName("setting_process")
                self.save_process = QtWidgets.QPushButton(self.centralwidget)
                self.save_process.setGeometry(QtCore.QRect(930, 390, 191, 51))
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.save_process.setFont(font)
                self.save_process.setStyleSheet(
                        "background-color: rgb(230, 230, 230);")
                self.save_process.setObjectName("save_process")
                self.test_2 = QtWidgets.QPushButton(self.centralwidget)
                self.test_2.setGeometry(QtCore.QRect(1039, 80, 131, 71))
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.test_2.setFont(font)
                self.test_2.setStyleSheet("background-color: rgb(255, 170, 0);")
                self.test_2.setObjectName("test_2")
                self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
                self.plainTextEdit.setGeometry(QtCore.QRect(40, 530, 871, 121))
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(16)
                self.plainTextEdit.setFont(font)
                self.plainTextEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
                self.plainTextEdit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                                "color: rgb(255, 255, 255);")
                self.plainTextEdit.setPlainText("")
                self.plainTextEdit.setObjectName("plainTextEdit")
                self.widget = QtWidgets.QWidget(self.centralwidget)
                self.widget.setGeometry(QtCore.QRect(40, 80, 871, 441))
                self.widget.setObjectName("widget")
                self.gridLayout = QtWidgets.QGridLayout(self.widget)
                self.gridLayout.setContentsMargins(0, 0, 0, 0)
                self.gridLayout.setObjectName("gridLayout")
                self.label_top_view = QtWidgets.QLabel(self.widget)
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(18)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.label_top_view.setFont(font)
                self.label_top_view.setStyleSheet(
                        "background-color: rgb(255, 255, 255);")
                self.label_top_view.setFrameShape(QtWidgets.QFrame.Panel)
                self.label_top_view.setLineWidth(2)
                self.label_top_view.setMidLineWidth(0)
                self.label_top_view.setObjectName("label_top_view")
                self.gridLayout.addWidget(self.label_top_view, 0, 0, 1, 1)
                self.label_sid_view = QtWidgets.QLabel(self.widget)
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(18)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.label_sid_view.setFont(font)
                self.label_sid_view.setStyleSheet(
                        "background-color: rgb(255, 255, 255);")
                self.label_sid_view.setFrameShape(QtWidgets.QFrame.Panel)
                self.label_sid_view.setLineWidth(2)
                self.label_sid_view.setMidLineWidth(0)
                self.label_sid_view.setObjectName("label_sid_view")
                self.gridLayout.addWidget(self.label_sid_view, 0, 1, 1, 1)
                self.widget1 = QtWidgets.QWidget(self.centralwidget)
                self.widget1.setGeometry(QtCore.QRect(930, 170, 258, 212))
                self.widget1.setObjectName("widget1")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setObjectName("verticalLayout")
                self.label_L_stpe = QtWidgets.QLabel(self.widget1)
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(16)
                self.label_L_stpe.setFont(font)
                self.label_L_stpe.setObjectName("label_L_stpe")
                self.verticalLayout.addWidget(self.label_L_stpe)
                self.textEdit_L = QtWidgets.QTextEdit(self.widget1)
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(16)
                self.textEdit_L.setFont(font)
                self.textEdit_L.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.textEdit_L.setObjectName("textEdit_L")
                self.verticalLayout.addWidget(self.textEdit_L)
                self.label_R_stpe = QtWidgets.QLabel(self.widget1)
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(16)
                self.label_R_stpe.setFont(font)
                self.label_R_stpe.setObjectName("label_R_stpe")
                self.verticalLayout.addWidget(self.label_R_stpe)
                self.textEdit_R = QtWidgets.QTextEdit(self.widget1)
                font = QtGui.QFont()
                font.setFamily("Tahoma")
                font.setPointSize(16)
                self.textEdit_R.setFont(font)
                self.textEdit_R.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.textEdit_R.setObjectName("textEdit_R")
                self.verticalLayout.addWidget(self.textEdit_R)
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
                self.menubar.setObjectName("menubar")
                self.menuFile = QtWidgets.QMenu(self.menubar)
                self.menuFile.setObjectName("menuFile")
                self.menuTool = QtWidgets.QMenu(self.menubar)
                self.menuTool.setObjectName("menuTool")
                self.menuSetting = QtWidgets.QMenu(self.menubar)
                self.menuSetting.setObjectName("menuSetting")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.action_Graph_process_Round_Time_s = QtWidgets.QAction(MainWindow)
                self.action_Graph_process_Round_Time_s.setObjectName("action_Graph_process_Round_Time_s")
                self.action_Graph_process_Round_Time_s.triggered.connect(self.activeSud.plot_graph_proecss_time)

                self.Graph_poor = QtWidgets.QAction(MainWindow)
                self.Graph_poor.setObjectName("chat_compare")
                self.Graph_poor.triggered.connect(self.activeSud.chart_compare)

                self.calculate_st = QtWidgets.QAction(MainWindow)
                self.calculate_st.setObjectName("calculate_st")
                self.calculate_st.triggered.connect(self.activeSud.st_win)

                self.process_chart = QtWidgets.QAction(MainWindow)
                self.process_chart.setObjectName("process_chart")

                self.menuTool.addAction(self.action_Graph_process_Round_Time_s)
                self.menuTool.addAction(self.Graph_poor)
                self.menuTool.addAction(self.calculate_st)
                self.menuTool.addAction(self.process_chart)

                self.menubar.addAction(self.menuFile.menuAction())
                self.menubar.addAction(self.menuTool.menuAction())
                self.menubar.addAction(self.menuSetting.menuAction())

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                self.pushButton_2.clicked.connect(self.start_video)
                self.pushButton_3.clicked.connect(self.stop_video)
                self.test.clicked.connect(self.start_fine_ArC)
                self.test_2.clicked.connect(self.start_fine_post)
                self.setting_process.clicked.connect(self.activeSud.keyPgpt)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.test.setText(_translate("MainWindow", "ทดสอบ ArUco"))
                self.pushButton_2.setText(_translate("MainWindow", "เริ่ม"))
                self.pushButton_3.setText(_translate("MainWindow", "หยุด"))
                self.setting_process.setText(_translate("MainWindow", "..."))
                self.save_process.setText(_translate(
                        "MainWindow", "บันทึกและเปลี่ยนแปลง"))
                self.test_2.setText(_translate("MainWindow", "ทดสอบ Body Tracking"))
                self.label_top_view.setText(_translate("MainWindow", "กล้องมุมบน"))
                self.label_sid_view.setText(_translate("MainWindow", "กล้องมุมข้าง"))
                self.label_L_stpe.setText(_translate(
                        "MainWindow", "ตำแหน่งขั้นตอนข้างซ้าย"))
                self.textEdit_L.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'Tahoma\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[]</p></body></html>"))
                self.label_R_stpe.setText(_translate(
                        "MainWindow", "ตำแหน่งขั้นตอนข้างขวา"))
                self.textEdit_R.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'Tahoma\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[]</p></body></html>"))
                self.menuFile.setTitle(_translate("MainWindow", "File"))
                self.menuTool.setTitle(_translate("MainWindow", "Tools"))
                self.action_Graph_process_Round_Time_s.setText(_translate("MainWindow", "&Graph process : Item/Time(s)"))
                self.Graph_poor.setText(_translate("MainWindow", "&chat_compare"))
                self.calculate_st.setText(_translate("MainWindow", "&Standard Time"))
                self.process_chart.setText(_translate("MainWindow", "&Process chart"))
                self.menuSetting.setTitle(_translate("MainWindow", "Setting"))

        
        def set_cap(self, cap):
                cap.set(cv2.CAP_PROP_FRAME_WIDTH,640)
                cap.set(cv2.CAP_PROP_FRAME_HEIGHT,480)
        
        def setPhoto(self,image, camLabel):
                try:
                        self.tmp = image
                        image = imutils.resize(image,width=640)
                        frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                        image = QImage(frame, frame.shape[1],frame.shape[0],frame.strides[0],QImage.Format_RGB888)
                        camLabel.setPixmap(QtGui.QPixmap.fromImage(image))

                except:
                        print("Stop Camera!")

        def update(self, nowtest = True):
                QtWidgets.QApplication.processEvents()
                # print("RUN!!!")

                if self.video0.isOpened():
                     img0, self.image0 = self.video0.read()
                     self.Procam.Top_cam(self.image0, self.process_l, self.process_r, test=nowtest)
                     self.setPhoto(self.image0, self.label_top_view)
                if self.video1.isOpened():
                     img1, self.image1 = self.video1.read()
                     self.Procam.Side_cam(self.image1)
                     self.setPhoto(self.image1, self.label_sid_view)

        def start_video(self):
                if not self.is_run:
                        self.video0 = cv2.VideoCapture(0, cv2.CAP_DSHOW)
                        self.video1 = cv2.VideoCapture(1, cv2.CAP_DSHOW)

                        self.set_cap(self.video0)
                        self.set_cap(self.video1)
                        
                        self.timeM.timeout.connect(self.update)
                        self.timeM.start(1)
                        self.is_run = True

        def start_fine_ArC(self):
                if not self.is_run:
                        self.video0 = cv2.VideoCapture(0, cv2.CAP_DSHOW)
                        self.video1 = cv2.VideoCapture(1, cv2.CAP_DSHOW)

                        self.set_cap(self.video0)
                        self.set_cap(self.video1)

                        self.timeM.timeout.connect(lambda: self.update(nowtest=False))
                        self.timeM.start(1)
                        self.timer_fine.start()
                        self.timer_fine.timeout.connect(self.stop_video)
                        self.is_run = True

        def start_fine_post(self):
                if not self.is_run:
                        self.video0 = cv2.VideoCapture(0, cv2.CAP_DSHOW)
                        self.video1 = cv2.VideoCapture(1, cv2.CAP_DSHOW)

                        self.set_cap(self.video0)
                        self.set_cap(self.video1)

                        self.timeM.timeout.connect(lambda: self.update(nowtest=False))
                        self.timeM.start(1)
                        self.timer_fine.start()
                        self.timer_fine.timeout.connect(self.stop_video)
                        self.is_run = True

        def stop_video(self):
                if self.is_run:
                        self.video0.release()
                        self.video1.release()
                        self.is_run = False
        
        # def get_name_lastname(self):
        #         self.get_n = self.lineEdit_name.text()
        #         self.process_l = self.lineEdit_left_step.text()
        #         self.process_r = self.lineEdit_right_step.text()


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.setWindowTitle("Time Study")
        self.setWindowIcon(QtGui.QIcon("icon.png"))  # เพิ่มไอคอนหน้าต่าง

    def closeEvent(self, event):
        # สร้าง QMessageBox แบบกำหนดเองเพื่อยืนยันการปิดหน้าต่าง
        close_dialog = QtWidgets.QMessageBox(self)
        close_dialog.setWindowTitle("Close Confirmation")
        close_dialog.setText("Are you sure you want to close the window?")
        close_dialog.setInformativeText("Any unsaved progress will be lost.")
        close_dialog.setIcon(QtWidgets.QMessageBox.Warning)  # เปลี่ยนไอคอนเป็น Warning
        close_dialog.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        close_dialog.setDefaultButton(QtWidgets.QMessageBox.No)

        # ตกแต่ง QMessageBox
        close_dialog.setStyleSheet("""
            QMessageBox {
                background-color: #f7f7f7;
                font-family: Arial;
                font-size: 14px;
            }
            QPushButton {
                background-color: #4CAF50;
                color: white;
                border: none;
                padding: 8px 16px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 14px;
                margin: 4px 2px;
                cursor: pointer;
                border-radius: 4px;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
            QPushButton:pressed {
                background-color: #3e8e41;
            }
        """)

        # รอการตอบกลับจากผู้ใช้
        reply = close_dialog.exec()

        if reply == QtWidgets.QMessageBox.Yes:
            event.accept()  # ยอมรับการปิดหน้าต่าง
            self.ui.stop_video()  # หยุดการทำงานที่จำเป็นก่อนปิด
        else:
            event.ignore()  # ยกเลิกการปิดหน้าต่าง


def main():
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
