# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_graph_process_time.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pgpt(object):
    def setupUi(self, Form):
        Form.setObjectName("Plot graph proecss time")
        Form.resize(640, 480)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 40, 581, 271))
        self.widget.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(30, 320, 451, 58))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_nameFile = QtWidgets.QLineEdit(self.widget1)
        self.line_nameFile.setObjectName("line_nameFile")
        self.gridLayout.addWidget(self.line_nameFile, 0, 0, 1, 1)
        self.pushButton_Browse = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Browse.setObjectName("pushButton_Browse")
        self.gridLayout.addWidget(self.pushButton_Browse, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Plot graph proecss time"))
        self.pushButton_Browse.setText(_translate("Form", "Browse.."))
        self.pushButton_2.setText(_translate("Form", "Doen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_pgpt()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
